### ISSUE TITLE
judge.toml 每次实验的内容是否能叠加而不是全部重新修改

### ISSUE THREAD

**Issue by ZewanHuang** [BUAA-SE-Compiling/miniSysY-tutorial#21]
考虑到存在标识符，judge.toml 的内容是不是每次新实验就叠加内容即可，比如这次是

```toml
[jobs.lexer]
image = { source = "dockerfile", path = ".", tag = "pre-lexer" }
```

如果下次标识符是 abc，能不能直接提交

```toml
[jobs.lexer]
image = { source = "dockerfile", path = ".", tag = "pre-lexer" }
[jobs.abc]
image = { source = "dockerfile", path = ".", tag = "pre-abc" }
```

（代码省略大部分细节）
